<template>
    <div class="">
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
        landing
        <br>
    </div>
</template>

<script setup>
definePageMeta({
    layout: 'main',
    // middleware: ["auth"]
})
</script>